version: '3'

services:
  app:
    container_name: app
    build: 'app/.'
    restart: unless-stopped
    ports:
      - "8000:8000"
  
  nginx:
    container_name: nginx
    build: 'nginx/.'
    restart: always
    ports: 
      - "80:8080"
